### ISSUE TITLE
Invalid formats allowed for the Netherlands

### ISSUE THREAD

**Issue by RoodFruit** [brick/postcode#18]
A postal code in the Netherlands can never start with a `0`. 

Current regex:
```regex
/^([0-9]{4})([A-Z]{2})$/
```

Suggestion:
```regex
/^([1-9][0-9]{3})([A-Z]{2})$/
```

**Comment by BenMorel** [comment]
Thank you for your report! Fixed in [0.4.1](https://github.com/brick/postcode/releases/tag/0.4.1).
