### ISSUE TITLE
Compatible with PHP 7.0?

### ISSUE THREAD

**Issue by Ardibee** [brick/postcode#2]
Hi! This looks like a really useful repo but your composer.json requires PHP v7.1, which is not the default version in Ubuntu Xenial (16-04).  Any chance it works on PHP v7.0?  That might increase the uptake if you could downgrade the composer requirement to PHP v7.0... Thanks.

**Comment by BenMorel** [comment]
Hi, unfortunately not, all my libraries require PHP 7.1 from now on.

Some reasons are given on [gophp71.org](https://gophp71.org/), and active support for PHP 7.0 [has been dropped](http://php.net/supported-versions.php) 2 weeks ago!

You can install PHP 7.1 on Ubuntu though, using the `ppa:ondrej/php` repository:
https://launchpad.net/~ondrej/+archive/ubuntu/php
