### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by jamiethompson** [brick/postcode#4]
https://github.com/brick/postcode/blob/9fa8925c140ca6c9c3f3cbef28a526ee1dc2d8db/src/PostcodeFormatter.php#L35

I've been running a parcel shipping service for the past 10 years which imports a millions of very badly formatted user provided addresses from eBay and other sources. In my experience, your previous solution of stripping anything other than 0-9A-Z is far more robust. People will provide their postal code using all kinds of characters as separators including "." and even "~" more often than you would imagine.

**Comment by jamiethompson** [comment]
It's an interesting point you raise in relation to UTF-8. It's an entirely valid point, although I can't say I've ever run into it in real-world usage. It's worth some further thought though.

I think that perhaps it could be argued that what should be considered a separator is use-case specific. In this sense, perhaps your more limited solution _is_ actually a better one and an application can perform other more specific cleanup prior to formatting.

**Comment by jamiethompson** [comment]
I've been thinking about this a lot recently. My opinion has changed. I think that you were indeed right to make the change to strip only a limited set of separators.

Any more aggressive cleansing, if required in a specific use can, can be done prior to passing the value in.

What do you think?

**Comment by BenMorel** [comment]
I quite agree with this, although I'm thinking about pushing it a bit farther: what about leaving the entire cleansing to the application?

Because removing only spaces and dashes means that "WC2E 9RZ" would pass, but the same string with a [no-break space](https://www.fileformat.info/info/unicode/char/00a0/index.htm) wouldn't, which might be surprising to someone relying on the defaut behaviour.

Leaving the entire cleansing to the application means that "WC2E 9RZ" would be considered invalid, forcing you to pass "WC2E9RZ". This might be even more confusing, I don't know.

Thoughts?

**Comment by jamiethompson** [comment]
I understand your reasoning but at the same time I think it would be confusing for the user if correctly formatted postcodes were not accepted. This would be true not just of UK postcodes but others like Polish where the format is NN-NNN

**Comment by BenMorel** [comment]
I guess we should indeed revert to the original behaviour: only strip spaces and hyphens, as these are the only 2 separators valid across all countries. Maybe the documentation can be made clearer about this, in particular the fact that other separators, including no-break space, will be considered invalid, and that it's up to the application to cleanse other characters as needed.

I've been thinking about more advanced solutions, including using preg's [Unicode character properties](https://www.php.net/manual/en/regexp.reference.unicode.php) to detect and accept all kinds of UTF-8 separators / punctuation chars while leaving out alphanumeric characters, but I feel like this would be pushing it too far, and that we should delegate this kind of cleansing to the application. One reason is that we wan't assume that the whole world is UTF-8.

If you're OK with this, I'll revert my commit above and tag a release for the new GB formatter alone.

**Comment by jamiethompson** [comment]
I like that your library is simple with clear responsibilities. I should have thought longer before opening this issue. I've enjoyed the discussion though.

Looking forward to seeing #5 released. Thanks again.

**Comment by BenMorel** [comment]
Commit reverted. Thanks for the discussion!
